apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-api
  template:
    metadata:
      labels:
        app: cloud-api
    spec:
      containers:
      - name: api-container
        image: ezekachinemerem31/cloud-native-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:securepassword@postgres-service:5432/microservicedb"
